import React from "react";
import App from "./App";

export const faq_text_arr = [
    <h4>Ofte stillede spørgsmål</h4>,
    'Her på siden kan du se de oftest stillede spørgsmål om Idag.',
    <br />,
    <a className={"link"} href="https://docs.google.com/forms/d/e/1FAIpQLSeUM87tKy54d2GRsYuM2ncTG9y_Y9-CNMQ2WFLffibKQ0Fxig/viewform">Har du brug for hjælp med et specifikt problem? Så klik her!</a>,
    <br />,
    <a className={"link"} href="https://docs.google.com/forms/d/e/1FAIpQLSemAAyyhrijFEvjAvSgNAPsCr17p9npwGWxXOWPSCa-dqlXUw/viewform">Har du feedback, forslag eller har du fundet en fejl? Så klik her!</a>,
    <br />,
    <h4>Hvad er Idag?</h4>,
    'Idéen bag Idag er enkel:',
    <br />,
    'Hvis du har brug for hjælp til indkøb, kan Idag hjælpe dig med at finde én i nærheden, som kan tage varerne med, når vedkommende alligevel skal handle ind i supermarkedet eller i mindre butikker.',
    <br />,
    'Det er altså helt almindelige privatpersoner som du og jeg, der tager varer med til andre. Indkøbene bliver lavet i lokale supermarkeder og butikker, så varerne ikke skal fragtes med lastbiler fra en anden del af landet og hjem til dig.',
    <br />,
    'Vi kalder denne løsning for kunde-til-kunde levering. Modellen bygger på tanken om at dele vores fælles ressourcer bedre. Det kalder man også deleøkonomi.',
    <br />,
    'Når en privatperson henter varer i en lokal butik, er der en række fordele:',
    <br />,
    '\u2219 Det kan ofte lade sig gøre at få varerne leveret meget hurtigt - og når det passer dig',
    <br />,
    '\u2219 Det er meget, meget dyrt at levere dagligvarer til døren på almindelig vis. Når du bestiller varer på et onlinesupermarked, kommer denne omkostning oven i varens pris. Derfor er det i sidste ende dig, der betaler',
    <br />,
    '\u2219 Det sparer masser af brændstof og pakkematerialer',
    <br />,
    '\u2219 Det er godt for fællesskabet',
    <br />,
    '\u2219 Du får mulighed for at møde én fra dit nærmiljø',
    <br />,
    '\u2219 Du støtter dit lokale butiksmiljø og vil blive ved med at kunne få service hos disse butikker',
    <br />,
    <h4>Hvor kan jeg få hjælp til indkøb?</h4>,
    '\u2219 Vi anbefaler ikke, at du beder om hjælp til levering fra butikker, der er længere end 10 km væk',
    <br />,
    <h4>Hvad kan jeg få hjælp til indkøb af?</h4>,
    'Hos Idag kan du få hjælp til indkøb og afhenting af dagligvarer.',
    <br />,
    '\u2219 Vi anbefaler, at du ikke får hjælp til flere dagligvarer, end der kan være i to indkøbsposer',
    <br />,
    '\u2219 Vi anbefaler ikke, at du beder om levering for mere end 250 kr. ad gangen',
    <br />,
    '\u2219 Vi anbefaler ikke, at du bruger os til indkøb af julemiddagen i sidste øjeblik, men i stedet bruger os til de mindre indkøb, du har brug for nu',
    <br />,
    <h4>Hvordan får jeg hjælp til mine indkøb hos Idag?</h4>,
    'Her er en trin-for-trin gennemgang af bestillingsprocessen. Husk, at du skal have adgang til din mobiltelefon, når du bestiller.',
    <br />,
    '1. Gå til https://leveringidag.dk og klik på den grønne knap på forsiden',
    <br />,
    '2. Beskriv, hvad du har brug for hjælp til på siden:',
    <br />,
    '\u2219 I hvilken butik skal varerne købes/hentes?',
    <br />,
    '\u2219 Hvad har du brug for? (Din indkøbsliste)',
    <br />,
    '\u2219 Leveringsadressen',
    <br />,
    '\u2219 En eventuel besked til din indkøbshjælper',
    <br />,
    '\u2219 Hvor længe kan du vente på varerne?',
    <br />,
    '\u2219 Dit fulde navn',
    <br />,
    '\u2219 Dit mobilnummer',
    <br />,
    '\u2219 På grund af Corona-krisen har vi valgt ikke at tilbyde levering inden for korte tidsintervaller, men kun på hele dage. Det er for at sikre, at flere kan få leveret de varer, de har brug for',
    <br />,
    '3. Når du har delt din indkøbsopgave, modtager du en SMS. Klik på linket i SMS’en, så vil hjælpere i dit nærområde få besked om din opgave og kunne se, at du har brug for deres hjælp.',
    <br />,
    '4. Når en anden bruger har accepteret at købe og levere dine varer, får du besked på SMS. Samtidigt får du også besked om et cirka tidspunkt for levering af varerne.',
    <br />,
    '5. Når den, der hjælper dig, kommer med varerne, foreslår vi, at I gør som følger:',
    <br />,
    '\u2219 Du modtager varer og kvittering af din indkøber',
    <br />,
    '\u2219 Tal om det, hvis der mangler varer fra indkøbslisten',
    <br />,
    '\u2219 Via MobilePay overfører du det udlæg, som indkøberen har haft',
    <br />,
    '\u2219 Husk at passe på hinanden - og hold afstand. Sådan passer vi bedst på hinanden',
    <br />,
    <h4>Hvad koster det at få hjælp til indkøb?</h4>,
    '\u2219 I øjeblikket er der et honorar på 35 kr. for indkøb og levering af varerne',
    <br />,
    '\u2219 Du må gerne give lidt i drikkepenge. Men det er frivilligt, og vi anbefaler, at du max giver 50 kr.',
    <br />,
    <h4>Hvordan betaler man?</h4>,
    '\u2219 Al betaling foregår direkte mellem den, der får hjælp til indkøb og den, der hjælper med indkøb',
    <br />,
    '\u2219 Når du bestiller, bedes du skrive, hvis du ikke har adgang til MobilePay',
    <br />,
    <h4>Hjælp andre med indkøb</h4>,
    'Her er en trin-for-trin gennemgang af, hvordan du handler ind for andre.',
    <br />,
    '1. Gå til https://leveringidag.dk og klik på den grå knap på forsiden',
    <br />,
    '2. Indtast bynavn eller postnummer for at søge efter ledige indkøbsopgaver i dit lokalområde. Du søger nu efter opgaver i en omkreds af 10 km. Du kan også se opgaver i nærheden af dig ved at skrive din adresse',
    <br />,
    '3. Er der en ledig opgave i dit område, kan du klikke på den og vælge at løse den',
    <br />,
    '4. Hvis der ikke er ledige opgaver i dit lokalområde, kan du i stedet abonnére på SMS-beskeder. Så får du en besked, når der er nye opgaver i dit lokalområde. Vi sender 1-5 SMS’er de dage, hvor der er ledige opgaver i dit område. For at abonnére på SMS’er fra os, skal du klikke på linket under søgefeltet og indtaste dit mobilnummer. Du kan altid afmedle dig via et link i SMS’en',
    <br />,
    <br />,
    <h6>Sidst redigeret - 25.03.2020</h6>




];

export default App;